version: '3'

networks:
    laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-oly-bet
    ports: 
        - "8098:80"
    volumes:
        - ./src:/var/www/html
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - php
      - mysql

    networks:
        - laravel

  mysql:
    image: mysql:5.7.29
    container_name: mysql-oly-bet
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: zero11
      MYSQL_ROOT_PASSWORD: zero11
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      args:
        - WITH_XDEBUG=true
      dockerfile: Dockerfile
    container_name: php-oly-bet
    volumes:
      - ./src:/var/www/html
      - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "9001:9001"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer-oly-bet
    volumes:
        - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
        - php
    networks:
        - laravel

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan-oly-bet
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
        - 8099:80
    environment:
        PMA_HOST: mysql
        MYSQL_USER: homestead
        MYSQL_PASSWORD: zero11
        MYSQL_USERNAME: homestead
        MYSQL_ROOT_PASSWORD: zero11
    restart: always
    depends_on:
      - mysql
    networks:
        - laravel